services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: holdly
      POSTGRES_PASSWORD: 4123
      POSTGRES_DB: holdly-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  pgdata:
  redis_data:
