services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: holdly
      POSTGRES_PASSWORD: 4123
      POSTGRES_DB: holdly-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
